## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import fnmatch 
import glob
import os

def build(bld):
    module = bld.create_ns3_module('applications', ['internet', 'config-store', 'tools', 'point-to-point'])
    module.source = [
        'model/bulk-send-application.cc',
        '../../scratch/workerQueue.cc',
	'model/onoff-application.cc',
        'model/packet-sink.cc',
        'model/ping6.cc',
        'model/radvd.cc',
        'model/radvd-interface.cc',
        'model/radvd-prefix.cc',
        'model/udp-client.cc',
        'model/udp-server.cc',
        #'model/seq-ts-header.cc',
        'model/udp-trace-client.cc',
        'model/packet-loss-counter.cc',
        'model/udp-echo-client.cc',
        'model/udp-echo-server.cc',
        'model/v4ping.cc',
	'model/simple-udp-application.cc',
        'helper/bulk-send-helper.cc',
        'helper/on-off-helper.cc',
        'helper/packet-sink-helper.cc',
        'helper/ping6-helper.cc',
        'helper/udp-client-server-helper.cc',
        'helper/udp-echo-helper.cc',
        'helper/v4ping-helper.cc',
		'model/rdma-client.cc',
		'helper/rdma-client-helper.cc',
        ]
    
    for dirpath, dirs, files in os.walk('./src/applications/astra-sim/'):
        if 'network_frontend' in dirpath:
            print(dirpath, files)
            continue
        for filename in fnmatch.filter(files, "*.cc"):
            file = os.path.join(dirpath, filename)
            file = file.replace("./src/applications/", "")
            module.source.append(file)

    applications_test = bld.create_ns3_module_test_library('applications')
    applications_test.source = [
        'test/udp-client-server-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'applications'
    headers.source = [
        'model/bulk-send-application.h',
        '../../scratch/workerQueue.h',
	'../../scratch/myHeader.h',
	'model/onoff-application.h',
        'model/packet-sink.h',
        'model/ping6.h',
        'model/radvd.h',
        'model/radvd-interface.h',
        'model/radvd-prefix.h',
        'model/udp-client.h',
        'model/udp-server.h',
        #'model/seq-ts-header.h',
        'model/udp-trace-client.h',
        'model/packet-loss-counter.h',
        'model/udp-echo-client.h',
        'model/udp-echo-server.h',
        'model/v4ping.h',
	'model/simple-udp-application.h',
        'helper/bulk-send-helper.h',
        'helper/on-off-helper.h',
        'helper/packet-sink-helper.h',
        'helper/ping6-helper.h',
        'helper/udp-client-server-helper.h',
        'helper/udp-echo-helper.h',
        'helper/v4ping-helper.h',
		'model/rdma-client.h',
		'helper/rdma-client-helper.h',
        ]

    for dirpath, dirs, files in os.walk('./src/applications/astra-sim/'):
        for filename in fnmatch.filter(files, '*.hh'):
            file = os.path.join(dirpath, filename)
            file = file.replace("./src/applications/", "")
            headers.source.append(file)

    bld.ns3_python_bindings()
