name: Clang-tidy for all HH files
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: Install clang-tidy
      run: sudo apt update && sudo apt install -yq clang-tidy
    # build project
    - name: Test Build and run clang-tidy
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . && find astra-sim/ -name '*.cc' -exec clang-tidy {} \;
