name: Clang-tidy Full Tree

on: [push, pull_request]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@0.01
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
